# TensorFlow Basic Syntax

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.3.0


In [3]:
hello = tf.constant("Hello")

In [4]:
world = tf.constant("World")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [7]:
with tf.Session() as sess:
    # with: no need to close session manually
    result = sess.run(hello+world)

In [8]:
print(result)

b'HelloWorld'


addition

In [9]:
a = tf.constant(10)

In [10]:
b = tf.constant(20)

In [11]:
type(a)

tensorflow.python.framework.ops.Tensor

In [12]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [13]:
print(result)

30


In [14]:
const = tf.constant(10)

In [15]:
fill_mat = tf.fill((4,4),10)

In [16]:
myzeros = tf.zeros((4,4))

In [17]:
myones = tf.ones((4,4))

In [19]:
myrandn = tf.random_normal((4,4),mean=0,stddev=1.0)

In [20]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [21]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

interactive session in notebook setting

In [22]:
sess = tf.InteractiveSession()

In [23]:
for op in my_ops:
    print(sess.run(op))

10
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[[-0.03910721 -1.92891836 -0.93899667  0.45053202]
 [ 0.19845933 -0.1485676  -0.95418328 -0.07717101]
 [-1.02367675  1.28240108  0.36957753 -1.31277323]
 [-1.16824901  0.89603627 -0.1503845  -0.91269588]]
[[ 0.13417375  0.80764019  0.3731159   0.40031087]
 [ 0.5006336   0.94038153  0.52335358  0.04643226]
 [ 0.4259634   0.75147295  0.01882696  0.26469815]
 [ 0.18446565  0.74444866  0.91998565  0.06594908]]


In [24]:
for op in my_ops:
    print(op.eval())

10
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[[ 0.32579353 -0.60309941  0.49847487  0.52174681]
 [ 1.45131075  0.19392417 -0.09684657 -0.00643076]
 [ 0.03213578 -0.11613092 -0.63603067 -0.52333152]
 [-2.23811245 -0.62005812  0.16499561  0.88556683]]
[[ 0.75972664  0.2298826   0.05190206  0.04172623]
 [ 0.61919379  0.99985361  0.71850336  0.74667013]
 [ 0.14131951  0.49156713  0.07741249  0.18896687]
 [ 0.24135625  0.61752546  0.72660685  0.75213861]]


matrix multiplication

In [25]:
a = tf.constant([[1,2],
                [3,4]])

In [26]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [27]:
b = tf.constant([[10],[100]])

In [28]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [29]:
result = tf.matmul(a,b)

In [30]:
sess.run(result)

array([[210],
       [430]])

In [31]:
result.eval()

array([[210],
       [430]])